export const products = [
  // LAPTOPS
  {
    title: "Apple MacBook Pro 14 M3",
    price: 2899,
    discountedPrice: 2799,
    discountPercentage: (((2899 - 2799) / 2899) * 100).toFixed(1),
    description: "Powerful laptop with M3 chip for developers and designers.",
    rating: 4.8,
    images: ["/images/MacBookPro14tumM3Pro181TBsilver-edited.webp"],
    brand: "Apple",
    category: "Laptops",
    ram: "16GB",
    processor: "Apple M3",
    screen: "14 inch Liquid Retina",
    memory: "512GB SSD",
    weight: 1.6,
  },
  {
    title: "Dell XPS 13 Plus",
    price: 1799,
    discountedPrice: 1699,
    discountPercentage: (((1799 - 1699) / 1799) * 100).toFixed(1),
    description: "Premium ultrabook with sleek design and OLED display.",
    rating: 4.5,
    images: ["/images/dell_xps_13_plus.webp"],
    brand: "Dell",
    category: "Laptops",
    ram: "16GB",
    processor: "Intel Core i7-1360P",
    screen: "13.4 inch OLED",
    memory: "1TB SSD",
    weight: 1.3,
  },
  {
    title: "ASUS ROG Strix G16",
    price: 1999,
    discountedPrice: null,
    discountPercentage: null,
    description: "High performance gaming laptop.",
    rating: 4.7,
    images: ["/images/asus_rog_strix_g16.png"],
    brand: "Asus",
    category: "Laptops",
    ram: "32GB",
    processor: "Intel Core i9-13980HX",
    screen: "16 inch 165Hz",
    memory: "1TB SSD",
    vram: "8GB",
    weight: 2.5,
  },
  {
    title: "Lenovo Legion 5 Pro",
    price: 1599,
    discountedPrice: 1499,
    discountPercentage: (((1599 - 1499) / 1599) * 100).toFixed(1),
    description: "Gaming laptop with RTX graphics.",
    rating: 4.6,
    images: ["/images/Lenovo-Legion-Pro-5-16IRX9_1XDhAR.webp"],
    brand: "Lenovo",
    category: "Laptops",
    ram: "16GB",
    processor: "AMD Ryzen 7 7745HX",
    screen: "16 inch 165Hz",
    memory: "512GB SSD",
    vram: "6GB",
    weight: 2.4,
  },
  {
    title: "HP Spectre x360 14",
    price: 1599,
    discountedPrice: 1499,
    discountPercentage: (((1599 - 1499) / 1599) * 100).toFixed(1),
    description: "Premium convertible laptop with OLED display.",
    rating: 4.6,
    images: ["/images/hp_spectre_x360_14.png"],
    brand: "HP",
    category: "Laptops",
    ram: "16GB",
    processor: "Intel Core i7",
    screen: "14 inch OLED",
    memory: "1TB SSD",
    weight: 1.4,
  },
  {
    title: "HP ENVY 15",
    price: 1399,
    discountedPrice: 1299,
    discountPercentage: (((1399 - 1299) / 1399) * 100).toFixed(1),
    description: "High-performance laptop for creative professionals.",
    rating: 4.4,
    images: ["/images/hp-15-envy.webp"],
    brand: "HP",
    category: "Laptops",
    ram: "16GB",
    processor: "Intel Core i7",
    screen: "15.6 inch FHD",
    memory: "512GB SSD",
    weight: 1.9,
  },
  {
    title: "MSI Stealth 15M",
    price: 1899,
    discountedPrice: 1799,
    discountPercentage: (((1899 - 1799) / 1899) * 100).toFixed(1),
    description: "Gaming laptop with NVIDIA RTX 3060 graphics.",
    rating: 4.7,
    images: ["/images/msi_stealth_15m.png"],
    brand: "MSI",
    category: "Laptops",
    ram: "16GB",
    processor: "Intel Core i7",
    screen: "15.6 inch FHD",
    memory: "1TB SSD",
    weight: 1.8,
  },
  {
    title: "MSI Modern 14",
    price: 999,
    discountedPrice: 949,
    discountPercentage: (((999 - 949) / 999) * 100).toFixed(1),
    description: "Lightweight laptop for everyday productivity.",
    rating: 4.3,
    images: ["/images/msi_modern_14.webp"],
    brand: "MSI",
    category: "Laptops",
    ram: "8GB",
    processor: "Intel Core i5",
    screen: "14 inch FHD",
    memory: "512GB SSD",
    weight: 1.3,
  },
  {
    title: "Rampage X15 Gaming",
    price: 1549,
    discountedPrice: 1449,
    discountPercentage: (((1549 - 1449) / 1549) * 100).toFixed(1),
    description: "Powerful gaming machine with high refresh display.",
    rating: 4.5,
    images: ["/images/Colorful-X15-XS-KV.png"],
    brand: "Rampage",
    category: "Laptops",
    ram: "16GB",
    processor: "AMD Ryzen 7",
    screen: "15.6 inch 144Hz",
    memory: "1TB SSD",
    weight: 2.1,
  },
  {
    title: "Acer Swift 5",
    price: 1249,
    discountedPrice: 1199,
    discountPercentage: (((1249 - 1199) / 1249) * 100).toFixed(1),
    description: "Thin and light laptop for daily use.",
    rating: 4.2,
    images: [
      "/images/acer-swift-5-sf514-56t-53tl-gigahertz-laptop-gigahertz-890245_1024x.webp",
    ],
    brand: "Acer",
    category: "Laptops",
    ram: "8GB",
    processor: "Intel Core i5",
    screen: "14 inch FHD",
    memory: "512GB SSD",
    weight: 1.2,
  },
  {
    title: "Acer Nitro 5",
    price: 1149,
    discountedPrice: 1099,
    discountPercentage: (((1149 - 1099) / 1149) * 100).toFixed(1),
    description: "Gaming laptop with strong performance.",
    rating: 4.5,
    images: ["/images/acer-nitro-5-17195.png"],
    brand: "Acer",
    category: "Laptops",
    ram: "16GB",
    processor: "Intel Core i7",
    screen: "15.6 inch FHD",
    memory: "1TB SSD",
    weight: 2.3,
  },

  // MONITORS
  {
    title: "Samsung Odyssey G7",
    price: 699,
    discountedPrice: 649,
    discountPercentage: (((699 - 649) / 699) * 100).toFixed(1),
    description: "27 inch curved 240Hz gaming monitor.",
    rating: 4.5,
    images: ["/images/in-odyssey-g7-g70d-ls27dg700ewxxl-545029869.avif"],
    brand: "Samsung",
    category: "Monitors",
    screen: "27 inch 240Hz QHD",
    weight: 6.5,
  },
  {
    title: "LG UltraGear 27GP850",
    price: 499,
    discountedPrice: null,
    discountPercentage: null,
    description: "Nano IPS 165Hz gaming monitor.",
    rating: 4.4,
    images: ["/images/LG-27GP850-B-Ultragear-Gaming-Monitor-27.webp"],
    brand: "LG",
    category: "Monitors",
    screen: "27 inch 165Hz QHD",
    weight: 5.8,
  },

  // GRAPHICS CARDS
  {
    title: "NVIDIA RTX 4070 Ti",
    price: 899,
    discountedPrice: 849,
    discountPercentage: (((899 - 849) / 899) * 100).toFixed(1),
    description: "High-end GPU for 1440p and 4K gaming.",
    rating: 4.7,
    images: [
      "/images/TUF-Gaming-GeForce-RTX-4070-Ti-OC-Edition-packaging-and-graphics-card.png",
    ],
    brand: "NVIDIA",
    category: "Graphics Cards",
    vram: "12GB GDDR6X",
    weight: 1.2,
  },
  {
    title: "AMD Radeon RX 7800 XT",
    price: 749,
    discountedPrice: 699,
    discountPercentage: (((749 - 699) / 749) * 100).toFixed(1),
    description: "Powerful AMD GPU for high performance gaming.",
    rating: 4.6,
    images: ["/images/Radeon RX 7800 XT Phantom Gaming 16GB OC(L1).png"],
    brand: "AMD",
    category: "Graphics Cards",
    vram: "16GB GDDR6",
    weight: 1.3,
  },

  // SSD
  {
    title: "Samsung 990 Pro 1TB",
    price: 179,
    discountedPrice: 169,
    discountPercentage: (((179 - 169) / 179) * 100).toFixed(1),
    description: "High speed NVMe Gen4 SSD.",
    rating: 4.8,
    images: ["/images/samsung-990-pro-gen-4-1tb.png"],
    brand: "Samsung",
    category: "SSD",
    memory: "1TB SSD",
    weight: 0.05,
  },
  {
    title: "WD Black SN850X 2TB",
    price: 249,
    discountedPrice: 229,
    discountPercentage: (((249 - 229) / 249) * 100).toFixed(1),
    description: "Fast NVMe SSD for gaming PCs.",
    rating: 4.7,
    images: [
      "/images/wd-black-sn850x-nvme-ssd-heatsink-front.png.thumb.1280.1280.png",
    ],
    brand: "Western Digital",
    category: "SSD",
    memory: "2TB SSD",
    weight: 0.05,
  },

  // RAM
  {
    title: "Corsair Vengeance 32GB DDR5",
    price: 199,
    discountedPrice: null,
    discountPercentage: null,
    description: "High performance DDR5 RAM kit.",
    rating: 4.7,
    images: ["/images/Vengeance-RGB-DDR5-2UP-32GB-GRAY_01.avif"],
    brand: "Corsair",
    category: "RAM",
    ram: "32GB DDR5",
    weight: 0.1,
  },
  {
    title: "Kingston Fury 16GB DDR4",
    price: 89,
    discountedPrice: null,
    discountPercentage: null,
    description: "Reliable DDR4 memory kit.",
    rating: 4.5,
    images: ["/images/kingston_fury.png"],
    brand: "Kingston",
    category: "RAM",
    ram: "16GB DDR4",
    weight: 0.1,
  },

  // PROCESSORS
  {
    title: "Intel Core i7-14700K",
    price: 449,
    discountedPrice: 419,
    discountPercentage: (((449 - 419) / 449) * 100).toFixed(1),
    description: "Latest generation Intel processor.",
    rating: 4.8,
    images: ["/images/n22417-png.png"],
    brand: "Intel",
    category: "Processors",
    processor: "14th Gen i7",
    weight: 0.08,
  },
  {
    title: "AMD Ryzen 9 7950X",
    price: 599,
    discountedPrice: 569,
    discountPercentage: (((599 - 569) / 599) * 100).toFixed(1),
    description: "High-end CPU for creators.",
    rating: 4.9,
    images: ["/images/amd_ryzen_9.webp"],
    brand: "AMD",
    category: "Processors",
    processor: "Ryzen 9",
    weight: 0.08,
  },

  // KEYBOARDS
  {
    title: "Logitech G Pro X Keyboard",
    price: 149,
    discountedPrice: null,
    discountPercentage: null,
    description: "Mechanical gaming keyboard.",
    rating: 4.6,
    images: ["/images/pro-clicky-gallery-1.png"],
    brand: "Logitech",
    category: "Keyboards",
    weight: 0.9,
  },
  {
    title: "Razer Huntsman V2",
    price: 189,
    discountedPrice: 179,
    discountPercentage: (((189 - 179) / 189) * 100).toFixed(1),
    description: "Optical mechanical gaming keyboard.",
    rating: 4.7,
    images: ["/images/gamenote_img_13_1703539818.png.webp"],
    brand: "Razer",
    category: "Keyboards",
    weight: 1.1,
  },

  // MOUSE
  {
    title: "Logitech G Pro X Superlight",
    price: 129,
    discountedPrice: 119,
    discountPercentage: (((129 - 119) / 129) * 100).toFixed(1),
    description: "Ultra lightweight gaming mouse.",
    rating: 4.8,
    images: [
      "/images/Logitech-G-Pro-X-SUPERLIGHT-G-PRO-Wireless-Bluetooth-Mouse-25K-HERO-Lightweight-Mechanical-Programmable-Button.webp",
    ],
    brand: "Logitech",
    category: "Mouses",
    weight: 0.06,
  },
  {
    title: "Razer DeathAdder V3",
    price: 99,
    discountedPrice: 89,
    discountPercentage: (((99 - 89) / 99) * 100).toFixed(1),
    description: "Ergonomic gaming mouse.",
    rating: 4.5,
    images: ["/images/razer_deathadder.webp"],
    brand: "Razer",
    category: "Mouses",
    weight: 0.07,
  },

  // HEADPHONES
  {
    title: "Sony WH-1000XM5",
    price: 349,
    discountedPrice: 329,
    discountPercentage: (((349 - 329) / 349) * 100).toFixed(1),
    description: "Noise cancelling wireless headphones.",
    rating: 4.9,
    images: ["/images/sony_wh-1000xm5.webp"],
    brand: "Sony",
    category: "Headphones",
    weight: 0.25,
  },
  {
    title: "SteelSeries Arctis Nova 7",
    price: 179,
    discountedPrice: 169,
    discountPercentage: (((179 - 169) / 179) * 100).toFixed(1),
    description: "Wireless gaming headset.",
    rating: 4.6,
    images: [
      "/images/arctis_nova_7p_black_pdp_img_buy_06.png__1920x1080_crop-fit_optimize_subsampling-2-195.png",
    ],
    brand: "SteelSeries",
    category: "Headphones",
    weight: 0.35,
  },
];
